/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */

/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    WebUI: {
      type: 'sst.aws.StaticSite';
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
